######################################################################
# Automatically generated by qmake (2.01a) Sun Jun 29 15:20:31 2008
######################################################################

+=
TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += config.h core.h redbook.h
FORMS += redbook.ui
SOURCES += config.cpp core.cpp main.cpp
QT += xml
