######################################################################
# Automatically generated by qmake (2.01a) Mon Jul 21 20:03:23 2008
######################################################################

QT+=xml
CONFIG+=uitools
TEMPLATE = app
TARGET = gaia
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += config.h core.h stack.h uiloader.h
FORMS += redbook.ui
SOURCES += config.cpp core.cpp main.cpp stack.cpp uiloader.cpp
RESOURCES += redbook.qrc
