######################################################################
# Automatically generated by qmake (2.01a) Mon Jul 21 20:03:23 2008
######################################################################

QT+=xml
CONFIG+=uitools
TEMPLATE = app
TARGET = redbook
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += config.h core.h logic.h
FORMS += redbook.ui
SOURCES += config.cpp core.cpp logic.cpp main.cpp
RESOURCES += redbook.qrc
